### ISSUE TITLE
Moodle template UVa v5 me da Error 5834 en Word para Windows

### ISSUE THREAD

**Issue by grovertapia** [juacas/MoodleQUIZ_template_UVa#1]
Hola, la plantilla "Moodle_template_UVa_v5.dotm" es genial, puesto que funciona en Word para Mac, sin embargo, en Word para Windows emerge una ventana con un mensaje de texto que dice: Se ha producido el error '5834' en tiempo de ejecución: El elemento con el nombre especificado no existe.

Por favor me podrían orientar para solucionarlo?.

Estoy trabajando con Windows 10 x64 y Word 2019

Gracias.

**Comment by juacas** [comment]
Hola, 
¿Ese error sale nada más abrir el documento o al hacer alguna secuencia de acciones?
¿El resto de operación de la plantilla funciona bien?
¿El idioma de Office es el Español internacional, Español de algún país, Inglés?

**Comment by grovertapia** [comment]
Hola, descargué la última versión que publicaste y ya funciona, gracias.

**Comment by AsistenteVirtual** [comment]
¡Hola!
Está excelente la plantilla.  ¡Muchas gracias¡
¿Hay alguna manera de realizar preguntas ensayo?

**Comment by juacas** [comment]
Con la plantilla no se puede. La plantilla está pensada para las preguntas que hay que generar en gran número.
No obstante, puede crear un _issue_ nuevo de petición de nueva funcionalidad por si algún voluntario quiere abordar esa funcionalidad.

**Comment by AsistenteVirtual** [comment]
¡Hola!
Esta es la primera vez que participo en este tipo de comunidades.  Estoy maravillada con toda tu amabilidad y la generosidad al compartir estos datos.  ¡Mil gracias!
Continuaré explorando.
¡Saludos!
