### ISSUE TITLE
Aplicar MoodleQUIZ_template_UVa a cuestionarios ya elaborados

### ISSUE THREAD

**Issue by grovertapia** [juacas/MoodleQUIZ_template_UVa#2]
Saludos, aquí va mi aporte, descubrí que la plantilla, mejor dicho que los Estilos de la plantilla se pueden aplicar directamente a las preguntas y tipos de respuestas que ya se tengan elaboradas, así nos ahorramos el trabajo de re-elaborarlas usando paso a paso las herramientas de la plantilla.

El proceso es simple:

- Primero debemos habilitar el Panel de estilos y luego
- Posicionar el cursor en la línea de texto de la pregunta o respuesta para darle el formato correspondiente
- Hacemos clic en el Estilo que necesitemos aplicar al tipo de pregunta y/o respuesta.

Al final, se logra el mismo resultado, sólo que nos habremos ahorrado el esfuerzo de escribir nuevamente lo que ya tenemos elaborado.
Espero que mi descripción sea comprensible.

Gracias por la plantilla, funciona de maravilla.
Ah, además no solo sirve para crear cuestionarios para Moodle, sino también para GoogleForms.

![PlantillaMoodle_Mac](https://user-images.githubusercontent.com/17665562/85939293-1d2f9a00-b8e2-11ea-9e14-47fa0b97b7b1.png)

**Comment by juacas** [comment]
Gracias por aportar.
Pero eso que describes es lo que hacen los botones de la plantilla "marcar", "verdadero/ falso", etc.
Desarrollé los botones para evitar usar el panel de estilos.
