### ISSUE TITLE
Error en pregunta Palabra faltante

### ISSUE THREAD

**Issue by pattyBuzz** [juacas/MoodleQUIZ_template_UVa#3]
Saludos, existe un error en el tipo de pregunta Palabra faltante, se marca el hueco pero al exportar no se convierte con los simbolos esperados que indica cuál es la respuesta.
He realizado todos los tipos de preguntas que tiene la plantilla y solo ese tipo de preguntas no marca la palabra de respuesta al exportar, por lo que se tiene qué modificar despues en el archivo de texto para marcar.

Me ha servido de mucho la plantilla, muchas gracias por tu aporte

**Comment by juacas** [comment]
Hola, gracias por probar la plantilla. He revisado su incidencia y en mi caso el formato generado es:
`// Start of question: MissingWordQ`
`Inserte una pregunta con una parte (palabra o frase) en blanco aquí. Recuerde seleccionar la(s) palabra(s) que quiere en {=blanco} y dar clic en el botón Marcar Hueco!`
Se puede observar cómo la marca {=blanco} sigue el formato correcto del formato GIFT. ¿Puede concretar un poco más en qué consiste el error?

**Comment by pattyBuzz** [comment]
Saludos...
Cuando se genera el formato no aparecen los signos de {=palabra} que indica que es la respuesta, solo aparece la palabra.
Voy hacer pruebas y te paso las imágenes

**Comment by AntonioChenoll** [comment]
Hola, 
A mí, a veces, me sucede lo mismo. Se soluciona volviendo a exportar el mismo documento.
Un saludo.
