### ISSUE TITLE
Formato Numeración

### ISSUE THREAD

**Issue by ander36900** [juacas/MoodleQUIZ_template_UVa#4]
¿cómo podemos seleccionar el formato de numeración de las respuestas?

en la plantilla aparece como única opción la forma "•", pero seria bueno poder escoger A, B, C, D.  sin que al marcar la opción correcta se reinicie la numeración.

**Comment by juacas** [comment]
Al marcar la opción correcta no se altera el orden de las respuestas. Por ejemplo, una pregunta en formato GIFT generada será:
`
// Start of question: SingleChoiceQ

Inserte la pregunta de Opción única aquí. Ej: ¿Cuál es una montaña de España? {
~Kjfasd
=Asdlkajlka
~Fdkhsadf
~dafasd
}
`
Observe que se mantiene el orden. Cuando importe esa pregunta en su LMS (Moodle u otros) será allí dónde puede decidir cómo se muestran a los alumnos (incluyendo numeración y orden de las opciones).
