### ISSUE TITLE
Plantilla Moodle

### ISSUE THREAD

**Issue by Jesrh85** [juacas/MoodleQUIZ_template_UVa#7]
Hola:
He intentado bajarme la plantilla (para Word) para crear preguntas de test y luego importarlas como archivo GIF desde el campus. Sin embargo, he ido tanto a la parte del foro donde está colgada la plantilla, así como a los módulos donde también está colgada, y me sale un error al intentar descargarla
![Fallo descarga plantilla (2)](https://user-images.githubusercontent.com/85224982/120457057-71ff4e80-c396-11eb-88a7-825a46bd43ed.png)

 Parece que la plantilla no está o ha desaparecido. ¿Me la podéis pasar de otro modo? Siempre que quiero añadir preguntas me la tengo que descargar de nuevo desde los módulos o foros de extensión universitaria, porque al grabarla en mi ordenador me da problemas (incluso grabándola con extensión de plantilla). Por eso siempre la tomo del "sitio de origen". 
Muchas gracias
Saludos

**Comment by juacas** [comment]
La plantilla está siempre disponible en GITHUB ya que es el repositorio donde la guardo como almacén principal. ¿Puedes indicarme qué pasos has intentado dar para descargarlo y qué URL es la que ha devuelto ese error 500? He repasado todos los enlaces que conozco y todos funcionan.

**Comment by Jesrh85** [comment]
Hola Juan Carlos:
Ahora he ido a https://extension.campusvirtual.uva.es/mod/forum/discuss.php?d=9844
Y luego a https://raw.githubusercontent.com/juacas/MoodleQUIZ_template_UVa/master/Moodle_template_UVa_v5.dotm
Y ahora mismo sí me ha dejado descargarla, pero, hace media o una hora, no, me salía ese error.

**Comment by juacas** [comment]
Debe haber sido un problema puntual de GitHub.com
